<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\StockManagement.Service\StockManagement.Service.csproj" />
    <ProjectReference Include="..\StockManagement.Interface\StockManagement.Interface.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Stock_Management</RootNamespace>
  </PropertyGroup>

</Project>
